### PR TITLE
Backend merge

### PR DESCRIPTION
**Pull request by Meetia**
Initial database and heroku server setup with sample data.

### CODE REVIEW

**Comment by Fripplebubby** [comment]
I don't think we should add the node modules to the repository - we'd be tracking changes to thousands of files for our dependencies that we'll (probably) never touch. Better to let NPM handle the dependencies.

To do this, we'll need a .gitignore file.

**Comment by Meetia** [comment]
Yeah didn't realize we had all our node modules in there. It would probably be best just to add the gitignore to master and have everyone pull

**Comment by Fripplebubby** [comment]
That might work, but I think once the files have been tracked (i.e. committed and pushed onto the branch) it is too late - they'll be in the repository forever. I suggest:
- Adding an additional commit deleting the files:
``` 
$ git rm -r node_modules/ 
$ git commit -m "untracked node_modules"
$ git push origin backend
```
Additionally, notice that there is merge conflict warning. This means we couldn't merge this branch into master even if we wanted to. If you view the backend branch on using the GitHub website, it tells you that 
```
This branch is 13 commits ahead, 3 commits behind master.
```
The branch being X commits ahead is a good thing - that's the point of a feature branch! But the fact that it is 3 commits behind is the problem. This means that between the time the backend branch was created and now, the master branch has also been changed (3 times). So, before trying to merge backend and master, we have to bring master's changes into backend:
```
$ git checkout backend
$ git pull origin master
```
But if you try to do this, you get a merge conflict. We'll need to talk about how to fix this later. The gist is that the two branches disagree about the state of a file, and you need to decide which is correct.

**Comment by yyang08** [comment]
I solved the merge conflicts, removed node_modules/ and unnecessary files, and added a .gitignore file. The minor semicolon errors are fixed as well.

**Comment by JohnyGall** [comment]
Remove unneeded code! It is clear that you used a tutorial to bootstrap the back end (which is fine) but there is a ton of a code in here that is not necessary as it is part of the tutorial.  All of this unnecessary code needs to be removed to keep the repo clean. Please see [this ticket](https://trello.com/c/G59QBG4j/9-project-hygiene-clean-up-back-end) for a list of what needs to be removed.

**Pull request merged**
